base_url:/iadoc/v1/prod/doc
#Auto Gennerate SQL
spring.aop.auto=true
spring.jpa.show-sql=false
spring.iadoc.driver-class-name=oracle.jdbc.OracleDriver
spring.iadoc.jdbc-url=jdbc:oracle:thin:@//10.0.4.51:1521/reportdb
spring.iadoc.username=IADOC
spring.iadoc.password=IADOC@2023
spring.iadoc.maximumPoolSize=20
spring.iadoc.connectionTimeout=3600000
spring.iadoc.idleTimeout=600000
spring.iadoc.minimumIdle=5
spring.iadoc.test-on-borrow=true
spring.iadoc.test-while-idle=true
spring.iadoc.time-between-eviction-runs-millis=3600000


## App Properties
#bezkoder.app.jwtSecret= bezKoderSecretKey
##bezkoder.app.jwtExpirationMs= 3600000
##bezkoder.app.jwtRefreshExpirationMs= 86400000
#
### For test
#bezkoder.app.jwtExpirationMs= 60000
#bezkoder.app.jwtRefreshExpirationMs= 120000

spring.servlet.multipart.max-request-size=2001MB
spring.servlet.multipart.max-file-size=2000MB
upload.directory.docEn=src/main/resources/document/docEn/
upload.directory.docLa=src/main/resources/document/docLa/

