base_url:/meet-law/prod/api/v1
spring.aop.auto=true
spring.jpa.show-sql=false
spring.iadoc.driver-class-name=oracle.jdbc.OracleDriver
spring.iadoc.jdbc-url=jdbc:oracle:thin:@//10.0.4.51:1521/reportdb
spring.iadoc.username=IADOC
spring.iadoc.password=IADOC@2023
spring.iadoc.maximumPoolSize=20
spring.iadoc.connectionTimeout=3600000
spring.iadoc.idleTimeout=600000
spring.iadoc.minimumIdle=5
spring.iadoc.test-on-borrow=true
spring.iadoc.test-while-idle=true
spring.iadoc.time-between-eviction-runs-millis=3600000

upload.directory.image=src/main/resources/image/