
base_url:/meet-law/prod/api/v1
#Auto Gennerate SQL
spring.aop.auto=true
spring.jpa.show-sql=false
spring.iadoc.driver-class-name=oracle.jdbc.OracleDriver
spring.iadoc.jdbc-url=jdbc:oracle:thin:@//10.0.4.51:1521/reportdb
spring.iadoc.username=IADOC
spring.iadoc.password=IADOC
spring.iadoc.maximumPoolSize=20
spring.iadoc.connectionTimeout=3600000
spring.iadoc.idleTimeout=600000
spring.iadoc.minimumIdle=5
spring.iadoc.test-on-borrow=true
spring.iadoc.test-while-idle=true
spring.iadoc.time-between-eviction-runs-millis=3600000

spring.servlet.multipart.max-request-size=500MB
spring.servlet.multipart.max-file-size=500MB

media.upload.url=${MEDIA_UPLOAD_URL:https://dehome.ldblao.la/mobile/QR/IMGMOBILE/iadoc/}
media.upload.url_pdf=${MEDIA_UPLOAD_URL_PDF:https://dehome.ldblao.la/mobile/QR/IMGMOBILE/iadoc/indexPDF.php}
media.upload.path=${MEDIA_UPLOAD_URL:https://dehome.ldblao.la/mobile/QR/IMGMOBILE/iadoc/uploads/}
file.upload-dir=/opt/app/uploads
